export const CARGAR_DATOS_USUARIO = 'CARGAR_DATOS_USUARIO';
export const CARGAR_DATOS_USUARIO_EXITO = 'CARGAR_DATOS_USUARIO_EXITO';
export const CARGAR_DATOS_USUARIO_ERROR = 'CARGAR_DATOS_USUARIO_ERROR';

export const ACTUALIZAR_DATOS_USUARIO = 'ACTUALIZAR_DATOS_USUARIO';
export const ACTUALIZAR_DATOS_USUARIO_EXITO = 'ACTUALIZAR_DATOS_USUARIO_EXITO';
export const ACTUALIZAR_DATOS_USUARIO_ERROR = 'ACTUALIZAR_DATOS_USUARIO_ERROR';
